namespace:
  name: sandbox
  
image:
  repository: salazarr/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 3111

livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz
